feat: playwright setup first step
virtualidentityag/caritas-rework-onlineBeratung-frontend pull request #10
Opened 2024-11-19 12:59 UTC by sfvcode

testing pipelines github actions

2024-11-19 12:59 UTC, vi-sudo commented
Task linked: [CONNECTA-297 Setup of Initial QA Automated Tests + Playwright Configuration](https://app.clickup.com/t/6656196/CONNECTA-297)

2024-11-21 15:41 UTC, koepferd requested changes

2024-11-21 15:41 UTC, koepferd commented on tests/registration/registration.spec.ts
> +	// usermame & password
```suggestion
	// username & password
```

2024-11-21 15:41 UTC, koepferd commented on tests/registration/registration.spec.ts
> +		.getByLabel(/Ich habe die Datenschutzerklä|I have the Privacy policy/)
Please check on what you are checking. Someone can change the texts in Weblate which will then result in failing tests and development work needed.

2024-11-21 15:41 UTC, koepferd commented on tests/registration/registration.spec.ts
> +		.getByLabel(/Ich habe die Datenschutzerklä|I have the Privacy policy/)
I would not recommend using .getByLabel in our setup

2024-11-21 15:41 UTC, koepferd commented on tests/login/login.spec.ts
> +	ensureLanguage(page);
We can start with this, but generally I would recommend having the tests working no matter what language is used.

2024-11-21 15:41 UTC, koepferd commented on tests/login/login.spec.ts
> +	await page.getByLabel(/(user\s?name|benutzername)/i).fill(username!);
Rather go with something like searching input with id "username"

2025-01-27 10:41 UTC, sfvcode commented on tests/login/login.spec.ts
> +	ensureLanguage(page);
fixed

2025-01-27 10:42 UTC, sfvcode commented on tests/registration/registration.spec.ts
> +		.getByLabel(/Ich habe die Datenschutzerklä|I have the Privacy policy/)
.getByLabel are only now in the skipped registration, they are going to be replaced when delete user method is done

2025-01-27 10:42 UTC, sfvcode commented on tests/login/login.spec.ts
> +	await page.getByLabel(/(user\s?name|benutzername)/i).fill(username!);
fixed

2025-01-27 11:14 UTC, Leandro13Silva13 approved these changes

2025-01-27 11:17 UTC, merged